### ISSUE TITLE
Recreate Routes Previously Developed in JavaScript

### ISSUE THREAD

**Issue by Jessika63** [Jessika63/PharmaXcess#60]
### **Description**
Reimplement all existing backend routes previously developed in JavaScript within the new Java Spring framework.

### **Tasks**

- [x]     Identify all routes in the current JavaScript backend.
- [x]     Create corresponding routes in Java Spring.
    - Redo user's routes & machines route
- [x]     Document each route and ensure consistency with previous versions.
